# Generated by Django 5.2.2 on 2025-06-10 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='provience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provience_name', models.CharField(max_length=200)),
                ('provience_code', models.CharField(max_length=10)),
                ('capital', models.CharField(max_length=20)),
            ],
        ),
    ]
