# Generated by Django 5.2.1 on 2025-06-13 08:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=25, unique=True)),
                ('phone_no', models.IntegerField(max_length=15)),
                ('contact_date', models.DateField(default=datetime.datetime(2025, 6, 13, 14, 41, 0, 589935))),
                ('address', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=250)),
            ],
        ),
    ]
